# Generated by Django 6.0.1 on 2026-06-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_board_boardstatus_sprint_task_comment_delete_todo"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("archived", "Archived")],
                default="active",
                max_length=20,
            ),
        ),
    ]
